apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arcee
  template:
    metadata:
      labels:
        app: arcee
    spec:
      containers:
        - name: arcee
          image: ghcr.io/overmindv/arcee:latest
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: arcee
            - secretRef:
                name: arcee
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
