// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	User      *User  `json:"user"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expiresAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Username  string  `json:"username"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	BirthDate *string `json:"birthDate,omitempty"`
	Phone     *string `json:"phone,omitempty"`
}

type UpdateUserInput struct {
	Username       *string `json:"username,omitempty"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	BirthDate      *string `json:"birthDate,omitempty"`
	ClearBirthDate *bool   `json:"clearBirthDate,omitempty"`
	Phone          *string `json:"phone,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	BirthDate *string `json:"birthDate,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}
