package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/overmindv/arcee/internal/auth"
	"github.com/overmindv/arcee/internal/delivery/graphql/generated"
	"github.com/overmindv/arcee/internal/delivery/graphql/model"
	"github.com/overmindv/arcee/internal/domain"
	"github.com/overmindv/arcee/internal/usecase"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	birthDate, err := parseBirthDate(input.BirthDate)
	if err != nil {
		return nil, err
	}
	result, err := r.Users.Register(ctx, usecase.RegisterInput{
		Email: input.Email, Password: input.Password, Username: input.Username,
		FirstName: stringValue(input.FirstName), LastName: stringValue(input.LastName),
		BirthDate: birthDate, Phone: stringValue(input.Phone),
	})
	if err != nil {
		return nil, err
	}
	return toAuthPayload(result), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	result, err := r.Users.Login(ctx, usecase.LoginInput{Email: input.Email, Password: input.Password})
	if err != nil {
		return nil, err
	}
	return toAuthPayload(result), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	actorID, err := auth.UserIDFromContext(ctx)
	if err != nil || actorID != id {
		if err == nil {
			err = domain.ErrUnauthorized
		}
		return nil, err
	}
	birthDate, err := parseBirthDate(input.BirthDate)
	if err != nil {
		return nil, err
	}
	user, err := r.Users.Update(ctx, usecase.UpdateUserInput{
		ID: id, Username: input.Username, FirstName: input.FirstName, LastName: input.LastName,
		BirthDate: birthDate, ClearBirthDate: boolValue(input.ClearBirthDate), Phone: input.Phone,
	})
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	actorID, err := auth.UserIDFromContext(ctx)
	if err != nil || actorID != id {
		if err == nil {
			err = domain.ErrUnauthorized
		}
		return false, err
	}
	if err := r.Users.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	id, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.Resolver.Users.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if _, err := auth.UserIDFromContext(ctx); err != nil {
		return nil, err
	}
	user, err := r.Resolver.Users.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*model.User, error) {
	if _, err := auth.UserIDFromContext(ctx); err != nil {
		return nil, err
	}
	users, err := r.Resolver.Users.List(ctx, intValue(limit, 20), intValue(offset, 0))
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, 0, len(users))
	for _, user := range users {
		result = append(result, toUser(user))
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
